version: '3.8'

services:
  filebrowser:
    image: crazykivi/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      # For Linux
      # - ./build/files:/srv
      # - ./builddb:/database
      # For windows
      - D:/filebrowser/filebrowser/build/files:/srv
      - D:/filebrowser/filebrowser/build/db:/database
    restart: unless-stopped